baseurl: https://leventerdor.netlify.app/about/
languageCode: en-us
theme: hugo-lithium

# title
title: Dor Leventer's Personal Site

# Details
name: Dor Leventer
role: PHD Economic Candidate

# Organization
organizations: 
  name: "Tel Aviv Univserity"
email: "dorleventer@mail.tau.ac.il"



googleAnalytics: ''
disqusShortname: ''

ignoreFiles:
  - \.Rmd$
  - \.Rmarkdown$
  - _cache$
  - \.knit\.md$
  - \.utf8\.md$
  
permalinks:
  post: /:year/:month/:day/:slug/
  
menu:
  main:
    - name: About
      url: /about/
      weight: 1
    - name: Research
      url: /research/
      weight: 2
    - name: Posts
      url: /post/
      weight: 3
    - name: GitHub
      url: https://github.com/dorlev3
      weight: 4
      
params:
  MathJaxCDN: //cdnjs.cloudflare.com/ajax/libs
  MathJaxVersion: 2.7.5
  description: The personal website of Dor Levetner.
  favicon: favicon.ico
  highlightjsCDN: //cdnjs.cloudflare.com/ajax/libs
  highlightjsLang:
    - r
    - yaml
  highlightjsTheme: github
  highlightjsVersion: 9.12.0
    
markup:
  defaultMarkdownHandler: goldmark
  goldmark:
    renderer:
      unsafe: yes
